=== clk11/proiect_tehnologii_web/xml/comanda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="COMANDA">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CUMPARATOR" type="xs:string" />
                <xs:element name="PRODUS" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="NUME" type="xs:string" />
                            <xs:element name="CANTITATE" type="xs:int" />
                            <xs:element name="DESCRIERE" minOccurs="0" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="500" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="PRET">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="valuta" use="required">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:enumeration value="RON" />
                                                        <xs:enumeration value="EUR" />
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id-produs" type="xs:string" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== clk11/proiect_tehnologii_web/xml/comanda.xml
<?xml version="1.0" encoding="UTF-8"?>

<COMANDA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="comanda.xsd">

     <CUMPARATOR>Marcel</CUMPARATOR>

    <PRODUS id-produs="1">
        <NUME>Laptop ACER</NUME>
        <CANTITATE>2</CANTITATE>
        <DESCRIERE> Fie ca va aflati acasa, la scoala sau la serviciu, obtineti toata performanta
            decare aveti nevoie cu cele mai recente procesoare Intel sau AMD; mentinand ordinea
            siasigurand functionarea constanta si fara probleme a aplicatiilor dvs. </DESCRIERE>
        <PRET valuta="RON">1999.99</PRET>
    </PRODUS>

    <PRODUS id-produs="2">
        <NUME>Televizor SAMSUNG</NUME>
        <CANTITATE>5</CANTITATE>
        <DESCRIERE> Vizionezi filmele si ai senzatia ca te afli acolo. PurColor permite
            televizorului sa redea o gama larga de culori, pentru o performanta optima a imaginii si
            o experienta de vizionare captivanta. </DESCRIERE>
        <PRET valuta="RON">1460.99</PRET>
    </PRODUS>

    <PRODUS id-produs="3">
        <NUME>Aparat de ras PHILIPS</NUME>
        <CANTITATE>2</CANTITATE>
        <PRET valuta="EUR">99.99</PRET>
    </PRODUS>
</COMANDA>
